services:
  training.repository.training:
    class: Training\Bundle\TrainingBundle\Repository\TrainingRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - Training\Bundle\TrainingBundle\Entity\Training

  training.repository.user_training:
    class: Training\Bundle\TrainingBundle\Repository\UserTrainingRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - Training\Bundle\TrainingBundle\Entity\UserTraining

  training.repository.exercise_video:
    class: Training\Bundle\TrainingBundle\Repository\ExerciseVideoRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - Training\Bundle\TrainingBundle\Entity\ExerciseVideo

  training.repository.exercise:
    class: Training\Bundle\TrainingBundle\Repository\ExerciseRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - Training\Bundle\TrainingBundle\Entity\Exercise
