version: '3.7'
services:
  db-fitnes:
    container_name: db-fitnes
    image: postgres
    restart: always
    ports:
      - '5435:5432'
    volumes:
      - ./docker/pddata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: db_password
      POSTGRES_ROOT_PASSWORD: db_password
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
    networks:
      - db-fitnes
  php-fitnes:
    container_name: php-fitnes
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/:cached
    depends_on:
      - db-fitnes
    networks:
      - db-fitnes
      - php-fitnes
  nginx-fitnes:
    container_name: nginx-fitnes
    build: docker/nginx
    ports:
      - "81:81"
    depends_on:
      - php-fitnes
    networks:
      - php-fitnes
    volumes:
      - ./:/var/www/:cached
      - ./docker/logs/nginx-back:/var/log/nginx:cached

volumes:
  fias_symfony_database:
networks:
  db-fitnes:
  php-fitnes:
